name: Ruff
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v1
        with:
          args: "check --select I"
          version: 0.11.8
      - uses: astral-sh/ruff-action@v1
        with:
          args: "format --check"
          version: 0.11.8
